window.mapData = {
    "name": "Battlefield",
    "players": 2,
    "dimensions": { "width": 16, "height": 8 },
    "tiles": [
      { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "capital p2" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "hill" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "mountain" }, { "type": "hill" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "forrest" }, { "type": "forrest" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "hill" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "capital p1" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" }, { "type": "grassland" },
      { "type": "grassland" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }, { "type": "water" }
    ],
    "cities": [
      { "x": 3, "y": 6, "owner": "p1" },
      { "x": 13, "y": 3, "owner": "p2" },
      { "x": 0, "y": 0, "owner": "neutral" },
      { "x": 0, "y": 1, "owner": "neutral" },
      { "x": 0, "y": 2, "owner": "neutral" },
      { "x": 0, "y": 3, "owner": "neutral" },
      { "x": 0, "y": 4, "owner": "neutral" },
      { "x": 0, "y": 5, "owner": "neutral" },
      { "x": 0, "y": 6, "owner": "neutral" },
      { "x": 0, "y": 7, "owner": "neutral" },
      { "x": 0, "y": 8, "owner": "neutral" },
      { "x": 1, "y": 1, "owner": "neutral" },
      { "x": 2, "y": 2, "owner": "neutral" },
      { "x": 3, "y": 3, "owner": "neutral" },
      { "x": 4, "y": 4, "owner": "neutral" },
      { "x": 5, "y": 5, "owner": "neutral" },
      { "x": 6, "y": 6, "owner": "neutral" },
      { "x": 7, "y": 7, "owner": "neutral" },
      { "x": 8, "y": 8, "owner": "neutral" },
      { "x": 9, "y": 8, "owner": "neutral" },
      { "x": 10, "y": 8, "owner": "neutral" },
      { "x": 11, "y": 8, "owner": "neutral" },
      { "x": 12, "y": 8, "owner": "neutral" },
      { "x": 13, "y": 8, "owner": "neutral" },
      { "x": 14, "y": 8, "owner": "neutral" },
      { "x": 15, "y": 8, "owner": "neutral" },
      { "x": 16, "y": 0, "owner": "neutral" },
      { "x": 16, "y": 1, "owner": "neutral" },
      { "x": 16, "y": 2, "owner": "neutral" },
      { "x": 16, "y": 3, "owner": "neutral" },
      { "x": 16, "y": 4, "owner": "neutral" },
      { "x": 16, "y": 5, "owner": "neutral" },
      { "x": 16, "y": 6, "owner": "neutral" },
      { "x": 16, "y": 7, "owner": "neutral" },
      { "x": 16, "y": 8, "owner": "neutral" }
    ]
};


  